<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>주요제품 | 비에이텍㈜</title>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Noto+Sans+KR:wght@300;400;500;700&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Header -->
    <header>
        <div class="header-container">
            <a href="index.html" class="logo">
                <span class="logo-kr">비에이텍㈜</span>
                <span class="logo-en">Blue Advanced Technology Co., Ltd.</span>
            </a>
            <nav>
                <ul>
                    <li><a href="intro.html">기업소개</a></li>
                    <li><a href="product.html" class="active">주요제품</a></li>
                    <li><a href="equipment.html">장비</a></li>
                    <li><a href="sales_history.html">업력</a></li>
                    <li><a href="map.html">찾아오시는 길</a></li>
                    <li><a href="inquiry.html">문의</a></li>
                </ul>
            </nav>
            <div class="hamburger" id="hamburgerBtn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
        <!-- Mobile Menu -->
        <div class="mobile-menu" id="mobileMenu">
            <a href="intro.html">기업소개</a>
            <a href="product.html">주요제품</a>
            <a href="equipment.html">장비</a>
            <a href="sales_history.html">업력</a>
            <a href="map.html">찾아오시는 길</a>
            <a href="inquiry.html">문의</a>
        </div>
    </header>

    <main>
        <!-- Page Hero -->
        <section class="page-hero">
            <div>
                <h1>주요 제품</h1>
                <p>Products & Solutions</p>
            </div>
        </section>

        <!-- Products Section -->
        <section class="section">
            <div class="filter-tabs">
                <div class="filter-tab active" data-filter="all">전체보기</div>
                <div class="filter-tab" data-filter="volute">벌류트펌프</div>
                <div class="filter-tab" data-filter="submersible">수중/오수펌프</div>
                <div class="filter-tab" data-filter="special">특수펌프 (부스터/심정용)</div>
            </div>

            <div class="product-grid" id="productGrid">
                <!-- Products will be generated by JS -->
            </div>
        </section>
    </main>

    <!-- Modal for Product Details -->
    <div class="modal-overlay" id="productModal">
        <div class="modal-content">
            <div class="modal-close" id="closeModal"><i class="fas fa-times"></i></div>
            <div class="modal-header">
                <h2 id="modalTitle">제품명</h2>
                <div class="modal-num" id="modalNum">제품번호</div>
            </div>
            <div class="modal-body">
                <p id="modalDesc">제품 설명이 들어갑니다.</p>
                <div style="background-color: var(--bg-color); padding: 20px; border-radius: 10px; margin-top: 20px;">
                    <p><strong>용도</strong> <span id="modalUsage">용도 설명</span></p>
                    <p><strong>특징</strong> <span id="modalFeatures">특징 설명</span></p>
                    <p><strong>구경</strong> <span id="modalSize">구경 정보</span></p>
                </div>
            </div>
            <div class="modal-footer">
                <a href="inquiry.html" class="btn btn-primary" id="modalInquiryBtn">이 제품 문의하기 <i class="fas fa-paper-plane" style="margin-left: 5px;"></i></a>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <div class="footer-container">
            <div>
                <div class="footer-logo-kr">비에이텍㈜</div>
                <div class="footer-logo-en">Blue Advanced Technology Co., Ltd.</div>
                <div class="footer-info">
                    <p><i class="fas fa-map-marker-alt"></i> <span>강원특별자치도 춘천시 퇴계공단2길 64 (퇴계제2농공단지내)</span></p>
                    <p><i class="fas fa-user-tie"></i> <span>대표이사: 조세연 | 사업자등록번호: 221-81-42625</span></p>
                    <p><i class="fas fa-phone"></i> <span>TEL: 033-264-9243 | FAX: 033-251-5747</span></p>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <p>Copyright © 비에이텍㈜. All rights reserved.</p>
        </div>
    </footer>

    <!-- Scripts -->
    <script>
        // Product Data
        const products = [
            {
                id: 'v1',
                category: 'volute',
                name: '편흡입 벌류트펌프',
                num: 'BA-V01',
                icon: 'fa-water',
                desc: '가장 널리 사용되는 범용 펌프로, 구조가 간단하고 취급이 용이하며 효율이 우수합니다.',
                usage: '일반 산업용수, 농사 및 급수, 공조 설비용',
                features: '높은 호환성, 간편한 유지보수, 저소음 설계',
                size: '40A ~ 300A'
            },
            {
                id: 'v2',
                category: 'volute',
                name: '양흡입 벌류트펌프',
                num: 'BA-V02',
                icon: 'fa-water',
                desc: '임펠러 양측에서 물을 흡입하여 대용량 이송에 적합하고 축 추력이 발생하지 않아 안정적입니다.',
                usage: '상하수도, 대규모 플랜트, 발전소 냉각수 이송',
                features: '대용량 이송, 긴 수명, 높은 효율성',
                size: '150A ~ 1000A'
            },
            {
                id: 's1',
                category: 'submersible',
                name: '수중 배수펌프',
                num: 'BA-S01',
                icon: 'fa-arrow-circle-down',
                desc: '모터와 펌프가 일체형으로 수중에 잠겨 작동하며, 소음이 없고 프라이밍(물채움)이 필요 없습니다.',
                usage: '지하 상가 배수, 농업용 관수, 정화조 배수',
                features: '완벽한 방수설계, 건식 모터 적용, 자동 운전 가능',
                size: '50A ~ 200A'
            },
            {
                id: 's2',
                category: 'submersible',
                name: '오물/오수펌프',
                num: 'BA-S02',
                icon: 'fa-recycle',
                desc: '고형물이 포함된 오수 처리를 위해 특수 설계된 논클로그(Non-Clog) 임펠러를 적용하였습니다.',
                usage: '하수처리장, 산업 폐수, 축산 농가 분뇨 처리',
                features: '막힘 방지 구조, 강력한 내마모성 재질, 대형 고형물 통과',
                size: '50A ~ 300A'
            },
            {
                id: 'sp1',
                category: 'special',
                name: '입형 다단 부스터펌프',
                num: 'BA-SP01',
                icon: 'fa-tachometer-alt',
                desc: '인버터 제어를 통해 사용량에 따라 회전수를 조절하여 일정한 수압을 유지하고 에너지를 절감합니다.',
                usage: '고층 아파트/빌딩 급수, 공장 가압수, 골프장 살수',
                features: '에너지 절감(최대 50%), 일정한 수압 유지, 콤팩트한 디자인',
                size: '25A ~ 150A'
            },
            {
                id: 'sp2',
                category: 'special',
                name: '심정용 수중펌프',
                num: 'BA-SP02',
                icon: 'fa-level-down-alt',
                desc: '지하 깊은 곳의 좁은 관정에 설치하기 위해 외경을 최소화하고 양정을 극대화한 다단 펌프입니다.',
                usage: '심관정(지하수) 취수, 온천수 양수, 농·어촌 식수원 개발',
                features: '고양정 실현, 스테인리스 스틸 재질, 내부식성 우수',
                size: '4인치 ~ 10인치 우물용'
            }
        ];

        // Mobile Menu Toggle
        const hamburgerBtn = document.getElementById('hamburgerBtn');
        const mobileMenu = document.getElementById('mobileMenu');

        hamburgerBtn.addEventListener('click', () => {
            mobileMenu.classList.toggle('show');
            const icon = hamburgerBtn.querySelector('i');
            if (mobileMenu.classList.contains('show')) {
                icon.classList.remove('fa-bars');
                icon.classList.add('fa-times');
            } else {
                icon.classList.remove('fa-times');
                icon.classList.add('fa-bars');
            }
        });

        // Product Rendering
        const productGrid = document.getElementById('productGrid');
        
        function renderProducts(filter) {
            productGrid.innerHTML = '';
            
            const filteredProducts = filter === 'all' 
                ? products 
                : products.filter(p => p.category === filter);
                
            filteredProducts.forEach(p => {
                const card = document.createElement('div');
                card.className = 'product-card';
                card.onclick = () => openModal(p.id);
                
                card.innerHTML = `
                    <div class="product-badge">${p.num}</div>
                    <div class="product-icon"><i class="fas ${p.icon}"></i></div>
                    <h3>${p.name}</h3>
                    <p class="product-desc">${p.desc}</p>
                    <div class="product-actions">
                        <button class="btn-inquiry" onclick="event.stopPropagation(); location.href='inquiry.html?product=${encodeURIComponent(p.name)}'">문의하기</button>
                        <span class="view-detail">상세보기 <i class="fas fa-chevron-right" style="font-size: 0.8rem;"></i></span>
                    </div>
                `;
                
                productGrid.appendChild(card);
            });
        }

        // Filter Logic
        const tabs = document.querySelectorAll('.filter-tab');
        tabs.forEach(tab => {
            tab.addEventListener('click', () => {
                // Remove active class from all
                tabs.forEach(t => t.classList.remove('active'));
                // Add active to clicked
                tab.classList.add('active');
                // Render products
                renderProducts(tab.dataset.filter);
            });
        });

        // Initial Render
        renderProducts('all');

        // Modal Logic
        const modal = document.getElementById('productModal');
        const closeModal = document.getElementById('closeModal');
        
        function openModal(id) {
            const p = products.find(prod => prod.id === id);
            if(p) {
                document.getElementById('modalTitle').innerText = p.name;
                document.getElementById('modalNum').innerText = p.num;
                document.getElementById('modalDesc').innerText = p.desc;
                document.getElementById('modalUsage').innerText = p.usage;
                document.getElementById('modalFeatures').innerText = p.features;
                document.getElementById('modalSize').innerText = p.size;
                document.getElementById('modalInquiryBtn').href = `inquiry.html?product=${encodeURIComponent(p.name)}`;
                
                modal.classList.add('show');
                document.body.style.overflow = 'hidden'; // Prevent background scrolling
            }
        }

        closeModal.addEventListener('click', () => {
            modal.classList.remove('show');
            document.body.style.overflow = 'auto';
        });

        // Close on clicking outside
        modal.addEventListener('click', (e) => {
            if(e.target === modal) {
                modal.classList.remove('show');
                document.body.style.overflow = 'auto';
            }
        });
    </script>
</body>
</html>
